# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
pool:
  name: nestor-pipeline-agent
  
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'atg-frontend-acr'
        repository: 'nestor-test'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
